/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2CM.h"
#include "I2CM_I2C.h"
#include "I2CM_PINS.h"
#include "I2CM_I2C_PVT.h"
#include "I2CM_PVT.h"
#include "I2CM_BOOT.h"
#include "BLE_gatt.h"
#include "BLE.h"
#include "BLE_HAL_PVT.h"
#include "BLE_STACK_PVT.h"
#include "BLE_StackGap.h"
#include "BLE_StackGatt.h"
#include "BLE_StackGattDb.h"
#include "BLE_StackHostMain.h"
#include "BLE_StackL2cap.h"
#include "BLE_StackGattServer.h"
#include "BLE_StackGattClient.h"
#include "BLE_Stack.h"
#include "BLE_eventHandler.h"
#include "BLE_custom.h"
#include "SW_TX.h"
#include "SW_TX_PVT.h"
#include "ISR_btn.h"
#include "Pin_button_isr.h"
#include "Pin_button_isr_aliases.h"
#include "ISR_hall.h"
#include "Pin_hall_sig.h"
#include "Pin_hall_sig_aliases.h"
#include "VCC_hall.h"
#include "VCC_hall_aliases.h"
#include "Pin_acc_isr.h"
#include "Pin_acc_isr_aliases.h"
#include "ISR_acc.h"
#include "Timer_1.h"
#include "ISR_everySecond.h"
#include "ADC.h"
#include "Vref.h"
#include "Vref_aliases.h"
#include "isr_CombinedPort.h"
#include "Pin_CombinedIntr.h"
#include "Pin_CombinedIntr_aliases.h"
#include "I2CM_SCBCLK.h"
#include "I2CM_sda.h"
#include "I2CM_sda_aliases.h"
#include "I2CM_scl.h"
#include "I2CM_scl_aliases.h"
#include "I2CM_SCB_IRQ.h"
#include "BLE_bless_isr.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

